### ISSUE TITLE
Make opening browser optional

### ISSUE THREAD

**Issue by okwolf** [okwolf/srvs#5]
Should the default behavior be open like it currently is or should users have to provide an argument like `--open`?

**Comment by Kimeiga** [comment]
I think it's ok for it to open by default, but I would have --noOpen as an option to prevent the browser from opening automatically.

**Comment by craftedsystems** [comment]
I prefer if it does not open a browser by default.

**Comment by okwolf** [comment]
What would you think of having an environment variable like `create-react-app` has [`BROWSER `](https://facebook.github.io/create-react-app/docs/advanced-configuration#docsNav)?

**Comment by Kimeiga** [comment]
Sounds cool!

**Comment by okwolf** [comment]
I implemented the env var option in version [`0.4.0`](https://github.com/okwolf/srvs/releases/tag/0.4.0).
