### ISSUE TITLE
docRoot should be . when the folder doesn't exist

### ISSUE THREAD

**Issue by Kimeiga** [okwolf/srvs#7]
This is up to you, but I think docRoot should be current directory by default instead of `public`.
This would reduce my calls from 
`srvs docRoot=.`
to 
`srvs` 🥇 

I don't know if hosting all files in `public` is best practice, but I usually host with Github pages, which I think requires the `index.html` to be either in the root of the project, or in `docs` folder.

What do you think Wolfgang?

**Comment by okwolf** [comment]
My hesitation with this one is that `public` is a commonly used folder for static web assets used by all kinds of other projects, perhaps most notably [`create-react-app`](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#using-the-public-folder) and I don't want to have to have `/public` prefix in most of my URLs. Perhaps just the `index.html` should allow for serving from `.`?

**Comment by Kimeiga** [comment]
Actually you make a good argument to keep it at public.

**Comment by okwolf** [comment]
A compromise might be to detect if a `public` folder exists and if not default to the current working directory.

**Comment by Kimeiga** [comment]
Sounds perfect!

**Comment by okwolf** [comment]
Released in [`0.5.0`](https://github.com/okwolf/srvs/releases/tag/0.5.0).
