### ISSUE TITLE
--hot on by default

### ISSUE THREAD

**Issue by Kimeiga** [okwolf/srvs#8]
Another enhancement, but I think it would really be magical if --hot was on by default, because I think most users would want to turn it on.

If all the enhancements go through, all you have to do to set up a quick webserver is cd to your project and:
`srvs`
to get hot reloading, current directory as root, and auto-open browser. That would literally be magical

**Comment by okwolf** [comment]
There might be a slight performance hit when hot reloading is on, not sure. There's definitely extra noise in your console if you're not using the feature.

**Comment by okwolf** [comment]
I'm a bit torn because webpack has this off by default, but Parcel seems to have it on with no way to disable it. I suppose the strongest argument for `--hot` on is that we don't need to do any building/bundling since all the transformations happen quickly on the fly.

**Comment by okwolf** [comment]
Released in [`0.5.0`](https://github.com/okwolf/srvs/releases/tag/0.5.0).
