### ISSUE TITLE
--hot for whole project rather than just /src

### ISSUE THREAD

**Issue by Kimeiga** [okwolf/srvs#9]
Yet another enhancement! It would be cool if `srvs` could watch for changes in `index.html`, `style.css`, and all code files in the project, rather than just files in `/src`

**Comment by okwolf** [comment]
Supporting other files is possible, but would be additional work that I don't currently have time for. If someone wants to contribute such an enhancement I'd be open.

**Comment by okwolf** [comment]
A poor-man's  hot reloading for the `docRoot` folder by refreshing the page has been published in version [`0.4.0`](https://github.com/okwolf/srvs/releases/tag/0.4.0).
